#!/bin/bash --

set -o pipefail

C_LIB=clib2
# For whatever reason, even when passing "static" to gcc during
# linking and the fact that our ADTOOLS compiler is meant to search
# for .a libraries in preference, if you link with -lstdc++ it will
# fail saying that it is trying to perform a static link with a
# dynamic object: stdc++.so. I have no idea why this it.
#
# Why are we even linking with stdc++? Because we compiled ICU with
#                                      C++ and it requires native
#                                      threading.
#
# To get around this, do not use the -l flag and just pass in the ".a"
# file directly; see "LIBS" below in the autogen flags.
#
# This is used for the directory where the libstdc++.a is located.
CPLUSPLUS_LIB="${C_LIB}"
# Too lazy to use getopts!
if (( ${#} > 0 ))
then
    if [[ "${1}" == "clib=newlib" ]]
    then
	C_LIB=newlib
	CPLUSPLUS_LIB="." # this may need changing; I think this is right, but not tried with newlib yet!
	echo 1>&2 "WARNING: Not sure if the value of \$CPLUSPLUS_LIB=${CPLUSPLUS_LIB} is actually correct for NEWLIB"
    elif [[ "${1}" != "clib=clib2" ]]
    then
	echo "Could not understand argument ${1}. Only clib=<newlib|clib2[default]> is understood" 1>&2
	exit 1
    fi
fi
INSTALL_PREFIX="$(pwd)/installAmiga_${C_LIB}"

which ppc-amigaos-gcc 1>/dev/null 2>&1 || { echo "ppc-amigaos-* binaries not found. Check your path" ; exit 1 ; }
if [[ "Linux" != "$(uname)" ]]
then
    echo "Expected the BUILD machine to be Linux"
    exit 1
fi

function create_amiga_SDK_package
{
    SDK_DIRS=(
	"local/${C_LIB}/bin"
	"local/${C_LIB}/lib"
	"local/${C_LIB}/share/libxml2/man"
	"local/${C_LIB}/share/libxml2/doc"
	"local/common/include"
    )

    for sdk_dir in "${SDK_DIRS[@]}"
    do
	mkdir -p "${sdk_dir}"
	find "${INSTALL_PREFIX}" -type d -iname "$(basename ${sdk_dir})" -exec cp -r {}/. "${sdk_dir}" \;
    done
    lha a libxml2_2.10.3.lha local/

}

./autogen.sh \
    --host=ppc-amigaos \
    --without-iconv \
    --with-icu \
    --without-python \
    --prefix="${INSTALL_PREFIX}" \
    --disable-shared \
    --enable-static \
    --disable-ipv6 \
    --with-zlib \
    --disable-silent-rules \
    CFLAGS="-mcrt=${C_LIB}" \
    CPPFLAGS="-mcrt=${C_LIB}" \
    CXXFLAGS="-mcrt=${C_LIB}" \
    LDFLAGS="-static -athread=native -mcrt=${C_LIB}" \
    LIBS="/sdk/../lib/${CPLUSPLUS_LIB}/libstdc++.a" \
    PKG_CONFIG_LIBDIR="/sdk/local/${C_LIB}/lib/pkgconfig" # ->
# Always add PKG_CONFIG_LIBDIR for Amiga cross compiles otherwise
# problems can arise. Sure, use the build machine's "pkg-config" tool
# but you must tell that tool where there Amiga's pgkconfig directory
# is, otherwise, pkg-config will go hunting around the build machine's
# pkgconfig directory which will cause all sorts of problems!

make -j$(nproc) 2>&1 | tee buildAmiga.log || { echo 1>&2 "ERROR: Failed to build LIBXML2" ; exit 1; }

make install

create_amiga_SDK_package

echo "FINISHED. See libxml2_2.10.3_.lha"

exit 0
