name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
          vs: [vs16, vc15]
          arch: [x64, x86]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - if: ${{matrix.vs == 'vs16'}}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: 14.28
      - if: ${{matrix.vs == 'vc15'}}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: 14.16
      - if: ${{matrix.vs == 'vs16'}}
        run: ./.github/workflows/build.ps1 -vs ${{matrix.vs}} -arch ${{matrix.arch}} -libiconv 1.16-4
      - if: ${{matrix.vs == 'vc15'}}
        run: ./.github/workflows/build.ps1 -vs ${{matrix.vs}} -arch ${{matrix.arch}} -libiconv 1.16-1
      - uses: actions/upload-artifact@v2
        with:
          name: libxml2-2.9.10-${{matrix.vs}}-${{matrix.arch}}
          path: ./winlib_build/
